# -*- coding: utf-8 -*-
"""TP_FINAL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JAI-bg_XHie686hsPNc-JyXelYdTUujn
"""

!pip install pandas requests scikit-learn tensorflow

pip install streamlit

!pip install keras-visualizer

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import requests
# import numpy as np
# from PIL import Image
# import tensorflow as tf
# from tensorflow.keras.preprocessing import image
# from tensorflow.keras.applications.inception_v3 import preprocess_input
# 
# modelo = tf.keras.models.load_model('/content/modelcnn.h5')
# 
# TARGET_SIZE = (224, 224)
# 
# def preprocess_image(img):
#     img = image.load_img(img, target_size=TARGET_SIZE)
#     img_array = image.img_to_array(img)
#     img_array = np.expand_dims(img_array, axis=0)
#     img_array = preprocess_input(img_array)
#     return img_array
# 
# def main():
#     st.title("De qué estilo es tu vestido?")
#     st.write("Ingrese el link de una imagen de un vestido para ver su estilo")
#     image_path = st.text_input("Enter Image URL to classify...")
# 
#     imagen_vestido = st.file_uploader("Cargar imagen de vestido", type=["jpg", "jpeg", "png"])
# 
#     if imagen_vestido:
#         st.image(imagen_vestido, caption="Imagen de vestido", use_column_width=True)
# 
#         processed_image = preprocess_image(imagen_vestido)
# 
#         resultado_prediccion = modelo.predict(processed_image)
# 
#         predicted_style_index = np.argmax(resultado_prediccion)
#         predicted_style = f"Estilo: {predicted_style_index}"
# 
#         st.write("Resultado de la predicción:")
#         st.write(predicted_style)
# 
# if __name__ == '__main__':
#     main()

!streamlit run app.py & npx localtunnel --port 8501

pip install --upgrade h5py tensorflow